Traceback (most recent call last):
  File "D:\MisTrabajos\Pytorch\pytorch\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "D:\MisTrabajos\Pytorch\pytorch\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\MisTrabajos\Pytorch\pytorch\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "D:\programas\Anaconda\envs\py310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\MisTrabajos\Pytorch\pytorch\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "D:\MisTrabajos\Pytorch\pytorch\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\MisTrabajos\Pytorch\pytorch\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from data_generation.nlp import ALICE_URL, WIZARD_URL, download_text
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[7], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdata_generation[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnlp[39;00m [38;5;28;01mimport[39;00m ALICE_URL, WIZARD_URL, download_text

File [1;32mD:\MisTrabajos\Pytorch\libro_pytorch\jupyters\data_generation\nlp.py:5[0m
[0;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01merrno[39;00m
[1;32m----> 5[0m [38;5;28;01mimport[39;00m [38;5;21;01mnltk[39;00m
[0;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnltk[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtokenize[39;00m [38;5;28;01mimport[39;00m sent_tokenize
[0;32m      8[0m ALICE_URL [38;5;241m=[39m [38;5;124m'[39m[38;5;124mhttps://ota.bodleian.ox.ac.uk/repository/xmlui/bitstream/handle/20.500.12024/1476/alice28-1476.txt[39m[38;5;124m'[39m

[1;31mModuleNotFoundError[0m: No module named 'nltk'

